import { ThemeModeScript } from "flowbite-react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeInit } from "../.flowbite-react/init";
import "./globals.css";
import { SidebarComponent, NavbarComponent } from "./components";
import { Toaster } from 'react-hot-toast';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Flowbite React Template Next.js",
  description: "Generated by create-flowbite-react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <head>
        {/*  <ThemeModeScript /> */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main>
          {/*  <ThemeInit /> */}
          {children}
          {/* Toaster global */}
          <Toaster
            position="top-right"
            toastOptions={{
              style: { fontSize: '14px' },
              success: { style: { background: 'green', color: 'white' } },
              error: { style: { background: 'red', color: 'white' } },
            }}
          />
        </main>
      </body>
    </html>
  );
}
